name        : libstartup-notification
version     : 0.12
release     : 5
source      :
    - http://www.freedesktop.org/software/startup-notification/releases/startup-notification-0.12.tar.gz : 3c391f7e930c583095045cd2d10eb73a64f085c7fde9d260f2652c7cb3cfbe4a
homepage    : http://freedesktop.org/wiki/Software/startup-notification
license     :
    - LGPL-2.0
summary     : Startup Notification libraries
component   : desktop.library
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xcb-aux)
description : |
    The startup-notification package contains startup-notification libraries. These are useful for building a consistent manner to notify the user through the cursor that the application is loading.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
